services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: blockchain-indexing-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: blockchain_indexing
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - blockchain-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Web Interface (Optional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: blockchain-indexing-mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - blockchain-net
    profiles:
      - debug

networks:
  blockchain-net:
    driver: bridge

volumes:
  mongo_data:
    driver: local 